# This is the configuration for pre-commit, a local framework for managing pre-commit hooks
#   Check out the docs at: https://pre-commit.com/

exclude: (\.min\.js$|\.svg$|\.html$)
default_stages: [commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-toml
      - id: check-yaml
        exclude: scripts/conda/recipe/meta.yaml
      - id: check-json
      - id: detect-private-key
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.7
    hooks:
      - id: ruff
        files: holonote/
      - id: ruff-format
        files: holonote/
  - repo: https://github.com/hoxbro/clean_notebook
    rev: v0.1.14
    hooks:
      - id: clean-notebook
        args: [--strip-trailing-newlines]
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
    - id: codespell
      additional_dependencies:
        - tomli
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: "v0.9.0.6"
    hooks:
      - id: shellcheck
