{% set data = load_file_data('../../pyproject.toml', from_recipe_dir=True) %}


package:
  name: holonote
  version: {{ VERSION }}

source:
  url: ../../dist/holonote-{{ VERSION }}-py3-none-any.whl

build:
  noarch: python
  script:
     - {{ PYTHON }} -m pip install -vv holonote-{{ VERSION }}-py3-none-any.whl

requirements:
  host:
    - python {{ data['project']['requires-python']}}

  run:
    - python {{ data['project']['requires-python']}}

    {% for dep in data['project']['dependencies'] %}
    - {{ dep.lower() }}
    {% endfor %}

test:
  imports:
    - holonote

about:
  license: BSD-3-Clause
  summary: {{ data['project']['description'] }}
  description: {{ data['project']['readme'] }}
